### ISSUE TITLE
메인화면에서 image 클릭하면 post 상세정보 출력

### ISSUE THREAD

**Issue by gyeongwon1275** [CodeSoom/project-react-3-gyeongwon1275#51]
메인화면에 출력된 image 를 클릭하면 해당 image 에 대한 상세정보를 표시

### front

- [x] 사용자는 이미지의 상세정보 및 좋아요 수, 싫어요 수, 댓글 수를 볼 수 있다.
  - [x] 메인 page 에서 이미지 클릭하면 이미지에서 가지고 있는 postId 로 history push 
  - [x] postDetail component 생성 ( content, image ) 
  - [x] postDetailPage 생성 (router 담당)
  - [x] postDetailContainer 생성 ( 댓글추가, 좋아요, 싫어요 등등 함수 관리 ) 
  - [x] getpost/:postId api 추가
  - [x] loadPost action 추가
  - [x] setPost reducer 추가
  - [x] post reducer 안에 post 상태 추가
  - [x] 작성시간과 현재시간 사이의 시간차이를 구하는 함수 추가 ( using date-fns ) 
       
### back

- [x] getpost router 추가

**Comment by Kihyun92** [comment]
이슈를 하나씩 등록하고 각 PR들로 처리하는게 좋네요 👍🏼 

다만 이 이슈는 상세페이지를 노출하는 기능이지만, 실제 작업양이 많을 것 같은데, 어떤 방식으로 PR 단위를 쪼개실지 궁금하네요 😊
